"""Write the feature registry (docs/p3/feature_registry.json + .md) from the code. No data needed.

    uv run python -m scripts.p3.export_registry

tests/test_p3_features.py::test_committed_registry_matches_code fails if the committed files are
stale, so the registry the team reads is always the one the pipeline uses.
"""

from __future__ import annotations

import json

from src.data.periods import ROOT
from src.features import compute as fc
from src.features import registry as reg

OUT = ROOT / "docs" / "p3"


def render(ctx: fc.FeatureContext) -> tuple[str, str]:
    recs = reg.registry_records(ctx)
    tool = [vars(f) | {"inputs": list(f.inputs), "as_of_tests": list(f.as_of_tests)}
            for f in reg.TOOL_ONLY.values()]  # fmt: skip
    doc = {
        "registry_sha256": reg.registry_hash(ctx),
        "lookback_hours": int(ctx.lookback.total_seconds() // 3600),
        "n_model_features": len(reg.model_features(ctx)),
        "features": [r | {"inputs": list(r["inputs"]), "as_of_tests": list(r["as_of_tests"])}
                     for r in recs],
        "tool_only": tool,
    }  # fmt: skip
    js = json.dumps(doc, indent=2) + "\n"
    lines = [
        "# P3 feature registry",
        "",
        "Generated by `scripts/p3/export_registry.py` from `src/features/registry.py`; do not "
        "edit by hand.",
        f"Registry sha256 `{doc['registry_sha256']}` · lookback {doc['lookback_hours']} h "
        f"(= frozen L_max) · {doc['n_model_features']} model features · owner {reg.OWNER}.",
        "",
        "Every model feature is covered by the as_of tests "
        + ", ".join(f"`{t}`" for t in reg.AS_OF_TESTS)
        + " (tests/test_p3_features.py), on the fixture and, for a 2,000-alert sample, on "
        "HI-Medium (`run_p3 check`).",
        "",
        "| # | name | group | definition | inputs | note |",
        "|---|---|---|---|---|---|",
    ]
    for i, r in enumerate(doc["features"], 1):
        lines.append(
            f"| {i} | `{r['name']}` | {r['group']} | {r['definition']} | "
            f"{', '.join(r['inputs'])} | {r['note']} |"
        )
    lines += ["", "## Not model features (tool only, MDP)", "",
              "| name | definition | inputs | note |", "|---|---|---|---|"]  # fmt: skip
    for r in tool:
        lines.append(f"| `{r['name']}` | {r['definition']} | {', '.join(r['inputs'])} | "
                     f"{r['note']} |")  # fmt: skip
    return js, "\n".join(lines) + "\n"


def main() -> int:
    js, md = render(fc.default_context())
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "feature_registry.json").write_bytes(js.encode("utf-8"))
    (OUT / "feature_registry.md").write_bytes(md.encode("utf-8"))
    print(f"wrote {OUT / 'feature_registry.json'} and .md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
